### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [vmxdev/sidmat#1]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [read_from_file](https://github.com/vmxdev/sidmat/blob/5296d96b05e294b54f334412cc239671c4dd0323/sidmat_common.h#L263)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [sidmat_init](https://github.com/vmxdev/sidmat/blob/5296d96b05e294b54f334412cc239671c4dd0323/sidmat_common.h#L284)

**Comment by vmxdev** [comment]
Fixed, thank you.

BTW, due to overcommit in Linux checking result of *alloc() functions is almost useless. More likely you will get segfault when accessing "succesfully" allocated memory.

I'm not advocating my inaccurate code, of course

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
